language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services: 
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE all_for_one; USE all_for_one;'