language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services: 
  - mysql
before_install:
  - mysql -u root --password=""
  - mysql -e 'CREATE DATABASE all_for_one;'
